/**
 * Generate public/scripts/pile/shapes-data.ts from the official mark pack SVGs.
 *
 * Reuses the exact body geometry shipped in public/images/marks/ (which is the
 * official grokbot-animation geometry) and extracts the eye slot layout
 * (center / radii / slant) so the pile can render eyes as separately
 * animatable dark slots.
 *
 * Run: bun run scripts/generate-pile-shapes.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MARKS_DIR = join(ROOT, 'public/images/marks');
const OUT_FILE = join(ROOT, 'public/scripts/pile/shapes-data.ts');

// The 9 app-picker shapes (product IDs) mapped to mark-pack filenames.
// See MARK-IDS-REFERENCE.md.
const PICKER_SHAPES: Array<{ id: string; pack: string }> = [
  { id: 'blob', pack: 'blob' },
  { id: 'egg', pack: 'circle' },
  { id: 'bean', pack: 'vertical-oval' },
  { id: 'squircle', pack: 'rounded-square' },
  { id: 'capsule', pack: 'horizontal-pill' },
  { id: 'wedge', pack: 'rounded-triangle' },
  { id: 'hex', pack: 'hexagon' },
  { id: 'cloud', pack: 'cloud' },
  { id: 'teardrop', pack: 'teardrop' },
];

interface EyeSpec {
  cx: number;
  cy: number;
  rx: number;
  ry: number;
  angle: number;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function extract(svg: string): { path: string; eyes: EyeSpec[] } {
  const dMatch = svg.match(/class="grok-bot-mark__compound"[^>]*\sd="([^"]+)"/);
  if (!dMatch) throw new Error('compound path not found');
  const d = dMatch[1];

  // Body = first subpath (up to and including its closing Z, before eye subpaths).
  const bodyEnd = d.search(/Z\s*M\s/);
  if (bodyEnd === -1) throw new Error('eye subpaths not found');
  const body = d.slice(0, bodyEnd + 1).trim();
  const eyesRaw = d.slice(bodyEnd + 1);

  // Eye subpaths are ellipses drawn as 4 arcs: M p0 A rx,ry rot 0,1 p1 ... Z
  const eyes: EyeSpec[] = [];
  const subpaths = eyesRaw.split(/(?=M\s)/).map((s) => s.trim()).filter(Boolean);
  for (const sp of subpaths) {
    const m0 = sp.match(/^M\s+(-?[\d.]+),(-?[\d.]+)/);
    if (!m0) continue;
    const arcRe = /A\s+(-?[\d.]+),(-?[\d.]+)\s+(-?[\d.]+)\s+0,1\s+(-?[\d.]+),(-?[\d.]+)/g;
    const pts: Array<[number, number]> = [[parseFloat(m0[1]), parseFloat(m0[2])]];
    let rx = 0;
    let ry = 0;
    let angle = 0;
    let am: RegExpExecArray | null;
    while ((am = arcRe.exec(sp)) !== null) {
      rx = parseFloat(am[1]);
      ry = parseFloat(am[2]);
      angle = parseFloat(am[3]);
      pts.push([parseFloat(am[4]), parseFloat(am[5])]);
    }
    // First 4 points sit on opposite quadrant pairs; their mean is the center.
    const four = pts.slice(0, 4);
    const cx = four.reduce((s, p) => s + p[0], 0) / four.length;
    const cy = four.reduce((s, p) => s + p[1], 0) / four.length;
    eyes.push({ cx: round2(cx), cy: round2(cy), rx, ry, angle });
  }
  if (eyes.length !== 2) throw new Error(`expected 2 eyes, got ${eyes.length}`);
  return { path: body, eyes };
}

const entries = PICKER_SHAPES.map(({ id, pack }) => {
  const file = join(MARKS_DIR, `grok-bot-${pack}-blue.svg`);
  const { path, eyes } = extract(readFileSync(file, 'utf8'));
  return { id, pack, path, eyes };
});

const lines: string[] = [];
lines.push('// AUTO-GENERATED by scripts/generate-pile-shapes.ts — do not edit by hand.');
lines.push('// Body paths are the official grokbot-animation mark geometry from');
lines.push('// public/images/marks/ (viewBox -15 -15 259 259, mark box 229x229).');
lines.push('');
lines.push('export interface PileEye {');
lines.push('  cx: number;');
lines.push('  cy: number;');
lines.push('  rx: number;');
lines.push('  ry: number;');
lines.push('  angle: number;');
lines.push('}');
lines.push('');
lines.push('export interface PileShape {');
lines.push('  /** app-picker product ID (blob, egg, bean, squircle, capsule, wedge, hex, cloud, teardrop) */');
lines.push('  id: string;');
lines.push('  /** mark-pack filename shape */');
lines.push('  pack: string;');
lines.push('  /** body outline subpath in mark coordinates */');
lines.push('  path: string;');
lines.push('  /** eye slots (contained dark pills) in mark coordinates */');
lines.push('  eyes: PileEye[];');
lines.push('}');
lines.push('');
lines.push('export const MARK_CENTER = 114.2705;');
lines.push('export const MARK_BOX = 229;');
lines.push('');
lines.push('export const PILE_SHAPES: PileShape[] = [');
for (const e of entries) {
  lines.push('  {');
  lines.push(`    id: ${JSON.stringify(e.id)},`);
  lines.push(`    pack: ${JSON.stringify(e.pack)},`);
  lines.push(`    path: ${JSON.stringify(e.path)},`);
  lines.push(
    `    eyes: [${e.eyes
      .map((eye) => `{ cx: ${eye.cx}, cy: ${eye.cy}, rx: ${eye.rx}, ry: ${eye.ry}, angle: ${eye.angle} }`)
      .join(', ')}],`,
  );
  lines.push('  },');
}
lines.push('];');
lines.push('');

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, lines.join('\n'));
console.log(`Wrote ${OUT_FILE} (${entries.length} shapes)`);
