/**
 * Generate public/scripts/pile/shapes-data.ts from the official mark pack SVGs.
 *
 * Reuses the exact body geometry shipped in public/images/marks/ (which is the
 * official grokbot-animation geometry) and extracts the eye slot layout
 * (center / radii / slant) so the pile can render eyes as separately
 * animatable dark slots.
 *
 * Run: bun run scripts/generate-pile-shapes.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MARKS_DIR = join(ROOT, 'public/images/marks');
const OUT_FILE = join(ROOT, 'public/scripts/pile/shapes-data.ts');

// The 9 app-picker shapes (product IDs) mapped to mark-pack filenames.
// See MARK-IDS-REFERENCE.md.
const PICKER_SHAPES: Array<{ id: string; pack: string }> = [
  { id: 'blob', pack: 'blob' },
  { id: 'egg', pack: 'circle' },
  { id: 'bean', pack: 'vertical-oval' },
  { id: 'squircle', pack: 'rounded-square' },
  { id: 'capsule', pack: 'horizontal-pill' },
  { id: 'wedge', pack: 'rounded-triangle' },
  { id: 'hex', pack: 'hexagon' },
  { id: 'cloud', pack: 'cloud' },
  { id: 'teardrop', pack: 'teardrop' },
];

interface EyeSpec {
  path: string;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function extract(svg: string): { path: string; eyes: EyeSpec[] } {
  const dMatch = svg.match(/class="grok-bot-mark__compound"[^>]*\sd="([^"]+)"/);
  if (!dMatch) throw new Error('compound path not found');
  const d = dMatch[1];

  // Find all Z positions - body ends at first Z, then two eye subpaths
  const zPositions: number[] = [];
  for (let i = 0; i < d.length; i++) {
    if (d[i] === 'Z') zPositions.push(i);
  }
  if (zPositions.length < 3) throw new Error(`expected 3 Z closures (body + 2 eyes), got ${zPositions.length}`);
  
  const body = d.slice(0, zPositions[0] + 1).trim();
  const eye1 = d.slice(zPositions[0] + 1, zPositions[1] + 1).trim();
  const eye2 = d.slice(zPositions[1] + 1, zPositions[2] + 1).trim();

  const eyes: EyeSpec[] = [{ path: eye1 }, { path: eye2 }];
  return { path: body, eyes };
}

const entries = PICKER_SHAPES.map(({ id, pack }) => {
  const file = join(MARKS_DIR, `grok-bot-${pack}-blue.svg`);
  const { path, eyes } = extract(readFileSync(file, 'utf8'));
  return { id, pack, path, eyes };
});

const lines: string[] = [];
lines.push('// AUTO-GENERATED by scripts/generate-pile-shapes.ts — do not edit by hand.');
lines.push('// Body paths are the official grokbot-animation mark geometry from');
lines.push('// public/images/marks/ (viewBox -15 -15 259 259, mark box 229x229).');
lines.push('');
lines.push('export interface PileEye {');
lines.push('  /** True eye path geometry (varies per shape) */');
lines.push('  path: string;');
lines.push('}');
lines.push('');
lines.push('export interface PileShape {');
lines.push('  /** app-picker product ID (blob, egg, bean, squircle, capsule, wedge, hex, cloud, teardrop) */');
lines.push('  id: string;');
lines.push('  /** mark-pack filename shape */');
lines.push('  pack: string;');
lines.push('  /** body outline subpath in mark coordinates */');
lines.push('  path: string;');
lines.push('  /** eye slots (contained dark pills) in mark coordinates */');
lines.push('  eyes: PileEye[];');
lines.push('}');
lines.push('');
lines.push('export const MARK_CENTER = 114.2705;');
lines.push('export const MARK_BOX = 229;');
lines.push('');
lines.push('export const PILE_SHAPES: PileShape[] = [');
for (const e of entries) {
  lines.push('  {');
  lines.push(`    id: ${JSON.stringify(e.id)},`);
  lines.push(`    pack: ${JSON.stringify(e.pack)},`);
  lines.push(`    path: ${JSON.stringify(e.path)},`);
  lines.push(`    eyes: [`);
  for (const eye of e.eyes) {
    lines.push(`      { path: ${JSON.stringify(eye.path)} },`);
  }
  lines.push(`    ],`);
  lines.push('  },');
}
lines.push('];');
lines.push('');

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, lines.join('\n'));
console.log(`Wrote ${OUT_FILE} (${entries.length} shapes)`);
